#!/bin/bash

echo -e "\e[31m 欢迎使用一键部署脚本 ！！！ \e[0m"]
package_path=
while [ ! -f "$package_path" ]
do
    read -p "请输入编译好的包，(相对路径)(如果不存在则会一直提示)" package_path
done
echo -e "\e[31m 当前包的路径为：$package_path \e[0m"
ssh root@162.14.122.254 "cd /opt/applications/SDS/sds-test && make stop-be"
scp -r "$package_path" root@162.14.122.254:/opt/applications/SDS/sds-test/backend/
ssh root@162.14.122.254 "cd /opt/applications/SDS/sds-test && make start-be-ps-logs"
echo -e "\e[32m 部署完毕 \e[0m"